name: dispatch to downstream repos for a new release

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  dispatch:
    runs-on: ubuntu-20.04

    steps:
      - name: dispatch to downstream repos when a new release is created
        run: |
          curl -X POST https://api.github.com/repos/wireapp/wire-ios/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.DISPATCH_SECRET }} \
          --data '{"event_type": "newRelease", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
